/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaServicesRouteImport } from './routes/visa-services'
import { Route as TravelInsuranceRouteImport } from './routes/travel-insurance'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as PassportServicesRouteImport } from './routes/passport-services'
import { Route as HotelBookingRouteImport } from './routes/hotel-booking'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AirTicketingRouteImport } from './routes/air-ticketing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as CountriesSchengenCountryRouteImport } from './routes/countries.schengen.$country'
import { Route as CountriesSlugVisaTypeRouteImport } from './routes/countries.$slug_.$visaType'

const VisaServicesRoute = VisaServicesRouteImport.update({
  id: '/visa-services',
  path: '/visa-services',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelInsuranceRoute = TravelInsuranceRouteImport.update({
  id: '/travel-insurance',
  path: '/travel-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportServicesRoute = PassportServicesRouteImport.update({
  id: '/passport-services',
  path: '/passport-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingRoute = HotelBookingRouteImport.update({
  id: '/hotel-booking',
  path: '/hotel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AirTicketingRoute = AirTicketingRouteImport.update({
  id: '/air-ticketing',
  path: '/air-ticketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSchengenCountryRoute =
  CountriesSchengenCountryRouteImport.update({
    id: '/countries/schengen/$country',
    path: '/countries/schengen/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSlugVisaTypeRoute = CountriesSlugVisaTypeRouteImport.update({
  id: '/countries/$slug_/$visaType',
  path: '/countries/$slug/$visaType',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/passport-services': typeof PassportServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/countries/$slug/$visaType': typeof CountriesSlugVisaTypeRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/passport-services': typeof PassportServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/countries/$slug/$visaType': typeof CountriesSlugVisaTypeRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/passport-services': typeof PassportServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/countries/$slug_/$visaType': typeof CountriesSlugVisaTypeRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/passport-services'
    | '/testimonials'
    | '/travel-insurance'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries/'
    | '/countries/$slug/$visaType'
    | '/countries/schengen/$country'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/passport-services'
    | '/testimonials'
    | '/travel-insurance'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries'
    | '/countries/$slug/$visaType'
    | '/countries/schengen/$country'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/passport-services'
    | '/testimonials'
    | '/travel-insurance'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries/'
    | '/countries/$slug_/$visaType'
    | '/countries/schengen/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirTicketingRoute: typeof AirTicketingRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HotelBookingRoute: typeof HotelBookingRoute
  PassportServicesRoute: typeof PassportServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TravelInsuranceRoute: typeof TravelInsuranceRoute
  VisaServicesRoute: typeof VisaServicesRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  CountriesSlugVisaTypeRoute: typeof CountriesSlugVisaTypeRoute
  CountriesSchengenCountryRoute: typeof CountriesSchengenCountryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa-services': {
      id: '/visa-services'
      path: '/visa-services'
      fullPath: '/visa-services'
      preLoaderRoute: typeof VisaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-insurance': {
      id: '/travel-insurance'
      path: '/travel-insurance'
      fullPath: '/travel-insurance'
      preLoaderRoute: typeof TravelInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-services': {
      id: '/passport-services'
      path: '/passport-services'
      fullPath: '/passport-services'
      preLoaderRoute: typeof PassportServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-booking': {
      id: '/hotel-booking'
      path: '/hotel-booking'
      fullPath: '/hotel-booking'
      preLoaderRoute: typeof HotelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-ticketing': {
      id: '/air-ticketing'
      path: '/air-ticketing'
      fullPath: '/air-ticketing'
      preLoaderRoute: typeof AirTicketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/schengen/$country': {
      id: '/countries/schengen/$country'
      path: '/countries/schengen/$country'
      fullPath: '/countries/schengen/$country'
      preLoaderRoute: typeof CountriesSchengenCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug_/$visaType': {
      id: '/countries/$slug_/$visaType'
      path: '/countries/$slug/$visaType'
      fullPath: '/countries/$slug/$visaType'
      preLoaderRoute: typeof CountriesSlugVisaTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirTicketingRoute: AirTicketingRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HotelBookingRoute: HotelBookingRoute,
  PassportServicesRoute: PassportServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TravelInsuranceRoute: TravelInsuranceRoute,
  VisaServicesRoute: VisaServicesRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  CountriesSlugVisaTypeRoute: CountriesSlugVisaTypeRoute,
  CountriesSchengenCountryRoute: CountriesSchengenCountryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
